"$schema" = "https://raw.githubusercontent.com/durocodes/audit/main/schema.json"

[[solutions]]
day = 1
part1 = "2769675"
part2 = "24643097"

[[solutions]]
day = 2
part1 = "660"
part2 = "689"

[[solutions]]
day = 3
part1 = "188741603"
part2 = "67269798"

[[solutions]]
day = 4
part1 = "2639"
part2 = "2005"

[[solutions]]
day = 5
part1 = "4609"
part2 = "5723"

[[solutions]]
day = 6
part1 = "4711"
part2 = "1562"
